apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes that creates the secrets and daemonset required for forge certificate authentication to the Artifactory Docker registry.
name: artifactory-forge-access
version: 0.1.0
