apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.forge.key.name }}
  namespace: kube-system
type: Opaque
data:
  {{ .Values.secrets.forge.key.name }}: {{ .Values.secrets.forge.key.value }}