apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.forge.cert.name }}
  namespace: kube-system
type: Opaque
data:
  {{ .Values.secrets.forge.cert.name }}: {{ .Values.secrets.forge.cert.value }}