apiVersion: v1
kind: Service
metadata:
  name: media-store
  labels:
{{ include "artifactory-forge-exemplar-services.labels" . | indent 4 }}
spec:
  selector:
    app: media-store
    app.kubernetes.io/name: {{ include "artifactory-forge-exemplar-services.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.mediaStore.port }}
    targetPort: {{ .Values.mediaStore.servicePort }}
  type: NodePort
