# Default values for docker-hub-hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nbelabsdocker
  tag: latest

imagePullSecrets:
  name: dockerhub-cred

secrets:
  dockerconfigjson: PASTE_THE_DOCKERCONFIGJSON_VALUE_HERE

nameOverride: ""
fullnameOverride: ""

mediaStore:
  port: 3000
  servicePort: 3000

audioProcessor:
  port: 3000
  servicePort: 3000
  env:
    host:
      name: MEDIA_STORE_SERVICE_HOST
      value: media-store
    port:
      name: MEDIA_STORE_SERVICE_PORT
      value: "3000"
